events {}

http {
  server {
    listen 80;

    location / {
      proxy_pass http://app-prod:3000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /dev/ {
      proxy_pass http://app-dev:3000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /staging/ {
      proxy_pass http://app-staging:3000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
